# Generated by Django 4.2.30 on 2026-06-18 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idea_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "time_available",
                    models.PositiveIntegerField(help_text="Available hours per week"),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Available budget in USD",
                        max_digits=12,
                    ),
                ),
                (
                    "skills",
                    models.TextField(
                        help_text="Comma-separated or plain text of existing skills"
                    ),
                ),
                ("goal", models.TextField(help_text="Goal or outcome")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem_statement", models.TextField()),
                ("target_audience", models.TextField()),
                ("value_proposition", models.TextField()),
                ("key_assumptions", models.JSONField(help_text="Key assumptions list")),
                ("feasibility_score", models.JSONField()),
                ("risks", models.JSONField()),
                ("scenarios", models.JSONField()),
                ("roadmap", models.JSONField()),
                ("first_action", models.TextField()),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        default="Medium",
                        max_length=10,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="planner.userproject",
                    ),
                ),
            ],
        ),
    ]
