# Generated by Django 4.2.30 on 2026-06-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectanalysis",
            name="is_fallback",
            field=models.BooleanField(default=False),
        ),
    ]
