# Generated by Django 4.2.30 on 2026-06-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_projectanalysis_is_fallback"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectanalysis",
            name="assumptions",
            field=models.JSONField(
                blank=True,
                help_text="Hidden assumptions validation recommendations",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectanalysis",
            name="confidence_reasoning",
            field=models.TextField(
                blank=True, default="", help_text="AI confidence explanation"
            ),
        ),
        migrations.AddField(
            model_name="projectanalysis",
            name="confidence_score",
            field=models.PositiveIntegerField(
                default=50, help_text="Confidence percentage 0-100"
            ),
        ),
        migrations.AddField(
            model_name="projectanalysis",
            name="generated_pdf_history",
            field=models.JSONField(
                blank=True, help_text="Log of generated PDF downloads", null=True
            ),
        ),
        migrations.AddField(
            model_name="projectanalysis",
            name="readiness_interpretation",
            field=models.TextField(
                blank=True, default="", help_text="AI rationale for readiness score"
            ),
        ),
        migrations.AddField(
            model_name="projectanalysis",
            name="readiness_score",
            field=models.PositiveIntegerField(
                default=0, help_text="Weighted overall readiness score 0-100"
            ),
        ),
        migrations.AddField(
            model_name="projectanalysis",
            name="risk_level",
            field=models.PositiveIntegerField(
                default=5, help_text="Overall risk level out of 10"
            ),
        ),
        migrations.AddField(
            model_name="projectanalysis",
            name="what_if_results",
            field=models.JSONField(
                blank=True, help_text="Sandbox cached simulation results", null=True
            ),
        ),
    ]
