# Generated by Django 4.2.30 on 2026-06-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0003_projectanalysis_assumptions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectanalysis",
            name="blind_spot_analysis",
            field=models.JSONField(
                blank=True,
                help_text="Weakness analysis highlighting cognitive blind spots and validation recommendations",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectanalysis",
            name="mentor_debate_results",
            field=models.JSONField(
                blank=True,
                help_text="Expert debate viewpoints from Builder, Investor, and Engineer",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectanalysis",
            name="opportunity_cost_analysis",
            field=models.JSONField(
                blank=True,
                help_text="Sacrifices vs benefits analysis, net score, and text summary",
                null=True,
            ),
        ),
    ]
